### ISSUE TITLE
HOLA!!! :)

### ISSUE THREAD

**Issue by maxlinux2000** [liturgiadelashoras/liturgiadelashoras.github.io#1]
Hola, soy massimo, el italiano que hablaba de programación con Luis (D.E.P.) por chat.

Hoy buscando otra cosa por github he visto este proyecto nuevo, y he visto que es el mismo de Luis, así que supongo que eres pariente o un amigo que se ha hecho cargo del mantenimiento.

he visto que la web original en argentina está desactualizada. Necesitas ayuda?
mi correo es: maxlinux2000@gmail.com

Si miras en el iPhone de luis en su telegram y whatsapp, verás nuestras conversaciones de programadores.... incluso hay preguntas que le había hecho a el antes de saber que había muerto.

saludos
MaX

**Comment by maxlinux2000** [comment]
bueno, cabe también al posibilidad que tu eres el venezolano que desarrolló la app en el playstore. Si es así me alegra mucho de verdad. Luis no ha conseguido encontrarte otra vez, y hemos pensado que había pasado lo peor, con lo que ocurre en Venezuela en estos últimos años.

De todas formas me alegra que tu sigas adelante! Y si necesitas ayuda, aquí me tienes

**Comment by geronimoarteaga** [comment]
La paz contigo Massimo... 

Gusto en conocerte... Soy el venezolano que desarrolló la app para Android hace 6 años... Gracias a sus oraciones sigo viviendo a pesar de las adversidades de mi país... Esperando en Dios con la intercesión de Luis Alberto continuar con su obra a través de esta grandiosa herramienta... 

Ya te escribí al correo electrónico para que tengas el mío... Dios te bendiga...!!!

Manuel G.
